In [1]:
import torch 
from torch import nn

In [2]:
# Tensors 
# pytorch opakowuje wielowymiarowe listy / macierze / tensory w swoją własną wewnętrzną strukturę danych Tensor 
data = [1,2,3]
tensor = torch.tensor(data)

In [3]:
#1 
# TODO: utwórzy tensor o wymiarach 2x2 o wartościach 1 [https://pytorch.org/docs/stable/generated/torch.ones.html#torch-ones]
# TODO: zapisz go do zmiennej tensor2d 
# TODO: wyświetl jego shape 
# TODO: Pomnóż nasz tensor2d przez 0.5 i zapisz wynik do tensor2d
tensor2d = torch.ones((2,2))
print(tensor2d.shape)
tensor2d = tensor2d * 0.5
print(tensor2d)

torch.Size([2, 2])
tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])


In [4]:
# TODO: Utwórz randomowy tensor 2x2 [https://pytorch.org/docs/stable/generated/torch.rand.html#torch.rand]
# TODO: przypisz go do zmiennej rand_tensor2d
# Pomnóż randomowy tensor z naszym poprzednim "połówkowym" tensorem 

rand_tensor2d = torch.rand((2,2))
torch.matmul(rand_tensor2d, tensor2d)

tensor([[0.4303, 0.4303],
        [0.5190, 0.5190]])

In [5]:
class MultiLayerPerceptronA(nn.Module):
    def __init__(self):
        super().__init__()        
        self.sigmoid = nn.Sigmoid()
        self.linear_layer1 = nn.Linear(10, 5)
        self.linear_layer2 = nn.Linear(5, 1)
        
    def forward(self, x):        
        x = self.linear_layer1(x)
        x = self.sigmoid(x)
        x = self.linear_layer2(x)
        x = self.sigmoid(x)
        return x

In [6]:
# utwórz instancję MultiLayerPerceptronA i przypisz do zmiennej model 
model = MultiLayerPerceptronA() # TODO 


In [7]:
# TODO: utwórz randomowy tensor o długości 10 i zaaplikuj na nim metodę forward() 
x = torch.rand(10)
model.forward(x)

tensor([0.5902], grad_fn=<SigmoidBackward0>)

In [8]:
# Alternatywną bardziej elegancką formą definiowania architektury jest użytwanie nn.Sequential 

class MultiLayerPerceptronB(nn.Module):
    def __init__(self):
        super().__init__()        
        self.mlp = nn.Sequential(
            nn.Linear(10, 5),
            nn.Sigmoid(),            
            nn.Linear(5,1),
            nn.Sigmoid()
        )
        
    def forward(self, x):        
        return self.mlp(x)

In [9]:
# TODO: Utwórz MLP jak w definicji zadania korzystając z nn.Sequential 

class MultiLayerPerceptron(nn.Module):
    def __init__(self):
        super().__init__()        
        self.mlp = nn.Sequential(
            nn.Linear(784, 50),
            nn.Sigmoid(),            
            nn.Linear(50, 15),
            nn.Sigmoid(),
            nn.Linear(15, 1),
            nn.Sigmoid(),
        )
    
    def forward(self, x):        
        return self.mlp(x)



In [10]:
# TODO: stwórz instancję modelu 
model = MultiLayerPerceptron()
model.forward(torch.rand(784))

tensor([0.7015], grad_fn=<SigmoidBackward0>)

In [11]:
# Parametry utworzonej sieci 
for name, param in model.named_parameters():
    if param.requires_grad:
        print(name)
        print(param.data)
        print()

mlp.0.weight
tensor([[ 0.0273, -0.0321, -0.0336,  ..., -0.0083,  0.0059,  0.0140],
        [ 0.0179, -0.0284, -0.0010,  ..., -0.0064,  0.0351, -0.0062],
        [-0.0119,  0.0264, -0.0016,  ...,  0.0052, -0.0175, -0.0327],
        ...,
        [ 0.0273, -0.0266, -0.0204,  ..., -0.0094,  0.0028, -0.0234],
        [ 0.0150, -0.0002,  0.0155,  ...,  0.0065,  0.0250, -0.0052],
        [ 0.0084, -0.0223,  0.0147,  ...,  0.0327, -0.0136, -0.0252]])

mlp.0.bias
tensor([ 0.0295,  0.0099, -0.0169,  0.0141,  0.0343,  0.0178, -0.0050, -0.0313,
        -0.0188,  0.0108, -0.0311, -0.0258, -0.0051, -0.0003, -0.0086, -0.0144,
        -0.0339, -0.0085, -0.0300, -0.0004,  0.0047,  0.0072,  0.0072, -0.0067,
        -0.0149,  0.0149,  0.0062,  0.0232, -0.0086,  0.0103,  0.0207,  0.0249,
         0.0299,  0.0178,  0.0208,  0.0301,  0.0123,  0.0221, -0.0228, -0.0013,
        -0.0274,  0.0239,  0.0119, -0.0231,  0.0064, -0.0245, -0.0314, -0.0120,
         0.0177, -0.0287])

mlp.2.weight
tensor([[-3.4973e-03

In [12]:
# Nasz model z wczoraj też może być wyrażony w Pytorch - technicznie to też "bardzo prosta" sieć neuronowa 

class ToyMLModel(nn.Module):
    def __init__(self):
        super().__init__()        
        self.mlp = nn.Sequential(
            nn.Linear(2, 1, bias=False)            
        )
        
    def forward(self, x):        
        return self.mlp(x)

toy = ToyMLModel()
state_dict = toy.state_dict()
state_dict['mlp.0.weight'] = torch.Tensor([[-12500, 24000]])
toy.load_state_dict(state_dict);


In [13]:
toy.forward(torch.Tensor([10, 40]))

tensor([835000.], grad_fn=<SqueezeBackward4>)